export default
// [
//     { _id: "A1", title: "New Assignment", course: "A1", available: "May 20 at 12:00am", 
//         due: "Due May 27 at 11:59pm", outdate: "2024-05-20", duedate: "2024-05-27", 
//         pts: "100", description: "New assignment" }, ...
// ]
[   
    { "_id": "A101", "title": "Rocket Propulsion Theory Assignment", "course": "RS101", "available": "May 6 at 12:00am", "due": "Due May 13 at 11:59pm", "outdate": "2024-05-06", "duedate": "2024-05-13", "pts": "100", "description": "Submit a detailed report on propulsion theory, including calculations of thrust and exhaust velocity for various fuel types. Include diagrams where necessary." },
    { "_id": "A102", "title": "Rocket Engine Design", "course": "RS101", "available": "May 13 at 12:00am", "due": "Due May 20 at 11:59pm", "outdate": "2024-05-13", "duedate": "2024-05-20", "pts": "100", "description": "Design a rocket engine and submit a presentation that explains the design choices. Focus on engine type, fuel, and performance." },
    { "_id": "A103", "title": "Rocket Fuel Analysis", "course": "RS101", "available": "May 20 at 12:00am", "due": "Due May 27 at 11:59pm", "outdate": "2024-05-20", "duedate": "2024-05-27", "pts": "100", "description": "Analyze different rocket fuels and write a comparison report, focusing on efficiency, cost, and environmental impact." },
    
    { "_id": "A201", "title": "Aerodynamics Quiz", "course": "RS102", "available": "May 6 at 12:00am", "due": "Due May 13 at 11:59pm", "outdate": "2024-05-06", "duedate": "2024-05-13", "pts": "100", "description": "This quiz covers key concepts of aerodynamics including airflow dynamics, lift, drag, and pressure distribution. Ensure you understand the fundamental principles as applied to aerospace design." },
    { "_id": "A202", "title": "Flow Analysis", "course": "RS102", "available": "May 13 at 12:00am", "due": "Due May 20 at 11:59pm", "outdate": "2024-05-13", "duedate": "2024-05-20", "pts": "100", "description": "For this assignment, analyze fluid flow patterns over an airfoil and through a nozzle. Use computational tools to visualize and explain key findings in the context of aerodynamics principles." },
    { "_id": "A203", "title": "Heating Analysis", "course": "RS102", "available": "May 20 at 12:00am", "due": "Due May 27 at 11:59pm", "outdate": "2024-05-20", "duedate": "2024-05-27", "pts": "100", "description": "This task requires you to assess thermal effects on aerospace materials under varying aerodynamic conditions. Conduct simulations to predict heat distribution and suggest ways to mitigate overheating." },

    { "_id": "A301", "title": "Structural Design Task", "course": "RS103", "available": "May 6 at 12:00am", "due": "Due May 13 at 11:59pm", "outdate": "2024-05-06", "duedate": "2024-05-13", "pts": "100", "description": "In this assignment, you will design a structural component for a spacecraft. Apply principles of stress analysis, material strength, and load distribution to ensure stability and safety." },
    { "_id": "A302", "title": "Orbital Calculations", "course": "RS103", "available": "May 13 at 12:00am", "due": "Due May 20 at 11:59pm", "outdate": "2024-05-13", "duedate": "2024-05-20", "pts": "100", "description": "Perform orbital mechanics calculations to determine satellite trajectories. Use relevant equations to model orbital transfer, velocity changes, and gravitational influences on space objects." },
    { "_id": "A303", "title": "Systems Engineering Exam", "course": "RS103", "available": "May 20 at 12:00am", "due": "Due May 27 at 11:59pm", "outdate": "2024-05-20", "duedate": "2024-05-27", "pts": "100", "description": "This exam assesses your understanding of systems engineering processes, including requirements analysis, system design, and project integration. Be prepared to apply both theoretical knowledge and practical solutions." },
    
    { "_id": "A110", "title": "Hydrocarbon Structures Report", "course": "RS104", "available": "May 6 at 12:00am", "due": "Due May 13 at 11:59pm", "outdate": "2024-05-06", "duedate": "2024-05-13", "pts": "100", "description": "Submit a detailed report on hydrocarbon structures and their chemical properties. Include a comparison of alkanes, alkenes, and alkynes." },
    { "_id": "A111", "title": "Stereochemistry Analysis", "course": "RS104", "available": "May 13 at 12:00am", "due": "Due May 20 at 11:59pm", "outdate": "2024-05-13", "duedate": "2024-05-20", "pts": "100", "description": "Analyze stereoisomers and write a report discussing their importance in biological systems. Include structural diagrams." },
    { "_id": "A112", "title": "Organic Reactions Lab", "course": "RS104", "available": "May 20 at 12:00am", "due": "Due May 27 at 11:59pm", "outdate": "2024-05-20", "duedate": "2024-05-27", "pts": "100", "description": "Conduct a lab experiment on organic reactions. Submit a lab report with detailed reaction mechanisms and experimental results." },
    
    { "_id": "A113", "title": "Coordination Chemistry Assignment", "course": "RS105", "available": "May 6 at 12:00am", "due": "Due May 13 at 11:59pm", "outdate": "2024-05-06", "duedate": "2024-05-13", "pts": "100", "description": "Write a paper on coordination chemistry, focusing on the properties and applications of metal complexes. Include diagrams and examples." },
    { "_id": "A114", "title": "Crystal Field Theory Project", "course": "RS105", "available": "May 13 at 12:00am", "due": "Due May 20 at 11:59pm", "outdate": "2024-05-13", "duedate": "2024-05-20", "pts": "100", "description": "Submit a project on crystal field theory, analyzing the structure of transition metal complexes. Include simulations or detailed calculations." },
     { "_id": "A115", "title": "Inorganic Synthesis Lab", "course": "RS105", "available": "May 20 at 12:00am", "due": "Due May 27 at 11:59pm", "outdate": "2024-05-20", "duedate": "2024-05-27", "pts": "100", "description": "Perform a lab synthesis of an inorganic compound and submit a detailed lab report with analysis and conclusions." },
    
    { "_id": "A116", "title": "Thermodynamics Problem Set", "course": "RS106", "available": "May 6 at 12:00am", "due": "Due May 13 at 11:59pm", "outdate": "2024-05-06", "duedate": "2024-05-13", "pts": "100", "description": "Complete a set of problems on thermodynamics, focusing on heat transfer and entropy. Submit detailed solutions." },
    { "_id": "A117", "title": "Quantum Mechanics Paper", "course": "RS106", "available": "May 13 at 12:00am", "due": "Due May 20 at 11:59pm", "outdate": "2024-05-13", "duedate": "2024-05-20", "pts": "100", "description": "Write a paper on the application of quantum mechanics in chemical reactions. Include mathematical models and experimental data where applicable." },
    { "_id": "A118", "title": "Spectroscopy Lab Report", "course": "RS106", "available": "May 20 at 12:00am", "due": "Due May 27 at 11:59pm", "outdate": "2024-05-20", "duedate": "2024-05-27", "pts": "100", "description": "Perform a spectroscopy experiment and submit a report analyzing the results and discussing the molecular properties observed." },
    
    { "_id": "A119", "title": "Digital Systems Analysis", "course": "RS107", "available": "May 6 at 12:00am", "due": "Due May 13 at 11:59pm", "outdate": "2024-05-06", "duedate": "2024-05-13", "pts": "100", "description": "Submit an analysis of a digital system, focusing on logic gates and state machines. Include diagrams and timing charts." },
    { "_id": "A120", "title": "Microprocessor Design Project", "course": "RS107", "available": "May 13 at 12:00am", "due": "Due May 20 at 11:59pm", "outdate": "2024-05-13", "duedate": "2024-05-20", "pts": "100", "description": "Design a microprocessor using VHDL or Verilog. Submit a simulation along with a report explaining your design choices and optimizations." },
    { "_id": "A121", "title": "Embedded Systems Lab", "course": "RS107", "available": "May 20 at 12:00am", "due": "Due May 27 at 11:59pm", "outdate": "2024-05-20", "duedate": "2024-05-27", "pts": "100", "description": "Write a report on the design of an embedded system, including code and performance analysis. Submit the source code and a working demonstration." },
    
    { "_id": "A122", "title": "VLSI Design Report", "course": "RS108", "available": "May 6 at 12:00am", "due": "Due May 13 at 11:59pm", "outdate": "2024-05-06", "duedate": "2024-05-13", "pts": "100", "description": "Analyze the design of a VLSI circuit. Submit a report with detailed diagrams and timing analysis, along with a performance comparison of alternative designs." },
    { "_id": "A123", "title": "ASIC Development Project", "course": "RS108", "available": "May 13 at 12:00am", "due": "Due May 20 at 11:59pm", "outdate": "2024-05-13", "duedate": "2024-05-20", "pts": "100", "description": "Develop an ASIC design using hardware description languages. Submit both a simulation and a report detailing design choices." },
    { "_id": "A124", "title": "FPGA Implementation Lab", "course": "RS108", "available": "May 20 at 12:00am", "due": "Due May 27 at 11:59pm", "outdate": "2024-05-20", "duedate": "2024-05-27", "pts": "100", "description": "Complete a lab assignment involving FPGA implementation. Submit the source code, along with a performance report and analysis." },
    
    { "_id": "A125", "title": "Signal Processing Assignment", "course": "RS109", "available": "May 6 at 12:00am", "due": "Due May 13 at 11:59pm", "outdate": "2024-05-06", "duedate": "2024-05-13", "pts": "100", "description": "Submit an assignment on signal processing techniques, focusing on digital filtering and Fourier analysis. Include MATLAB or Python code where applicable." },
    { "_id": "A126", "title": "Communication Systems Design", "course": "RS109", "available": "May 13 at 12:00am", "due": "Due May 20 at 11:59pm", "outdate": "2024-05-13", "duedate": "2024-05-20", "pts": "100", "description": "Design a digital communication system and submit both a simulation and a report. Focus on error correction, modulation schemes, and data throughput." },
    { "_id": "A127", "title": "Wireless Systems Project", "course": "RS109", "available": "May 20 at 12:00am", "due": "Due May 27 at 11:59pm", "outdate": "2024-05-20", "duedate": "2024-05-27", "pts": "100", "description": "Submit a project on wireless communication systems, focusing on protocol design, antenna placement, and bandwidth efficiency." },
    
    { "_id": "A128", "title": "Database Design Assignment", "course": "RS110", "available": "May 6 at 12:00am", "due": "Due May 13 at 11:59pm", "outdate": "2024-05-06", "duedate": "2024-05-13", "pts": "100", "description": "Design a database schema for a retail company. Submit the SQL code, along with an ER diagram and a normalization analysis." },
    { "_id": "A129", "title": "SQL Optimization Lab", "course": "RS110", "available": "May 13 at 12:00am", "due": "Due May 20 at 11:59pm", "outdate": "2024-05-13", "duedate": "2024-05-20", "pts": "100", "description": "Complete a lab on SQL query optimization. Submit both the optimized queries and a report discussing the performance improvements achieved." },
    { "_id": "A130", "title": "Distributed Database Project", "course": "RS110", "available": "May 20 at 12:00am", "due": "Due May 27 at 11:59pm", "outdate": "2024-05-20", "duedate": "2024-05-27", "pts": "100", "description": "Develop a distributed database system and submit both the design and implementation report. Focus on replication, partitioning, and fault tolerance." },
    
    { "_id": "A131", "title": "Artificial Intelligence Algorithms", "course": "RS111", "available": "May 6 at 12:00am", "due": "Due May 13 at 11:59pm", "outdate": "2024-05-06", "duedate": "2024-05-13", "pts": "100", "description": "Implement AI algorithms such as decision trees, neural networks, or reinforcement learning. Submit both the source code and a report on performance metrics." },
    { "_id": "A132", "title": "Machine Learning Model Evaluation", "course": "RS111", "available": "May 13 at 12:00am", "due": "Due May 20 at 11:59pm", "outdate": "2024-05-13", "duedate": "2024-05-20", "pts": "100", "description": "Train and evaluate a machine learning model using Python or R. Submit a report analyzing accuracy, precision, recall, and model complexity." },
    { "_id": "A133", "title": "Natural Language Processing Project", "course": "RS111", "available": "May 20 at 12:00am", "due": "Due May 27 at 11:59pm", "outdate": "2024-05-20", "duedate": "2024-05-27", "pts": "100", "description": "Develop a Natural Language Processing (NLP) application using techniques like tokenization, named entity recognition, and sentiment analysis." },
    
        
    { "_id": "A134", "title": "Cybersecurity Threat Assessment", "course": "RS112", "available": "May 6 at 12:00am", "due": "Due May 13 at 11:59pm", "outdate": "2024-05-06", "duedate": "2024-05-13", "pts": "100", "description": "Conduct a threat assessment on a given network and submit a report detailing potential vulnerabilities and security measures." },
    { "_id": "A135", "title": "Encryption Algorithms Analysis", "course": "RS112", "available": "May 13 at 12:00am", "due": "Due May 20 at 11:59pm", "outdate": "2024-05-13", "duedate": "2024-05-20", "pts": "100", "description": "Analyze different encryption algorithms and write a report on their strengths, weaknesses, and use cases. Include examples of cryptographic code." },
    { "_id": "A136", "title": "Penetration Testing Lab", "course": "RS112", "available": "May 20 at 12:00am", "due": "Due May 27 at 11:59pm", "outdate": "2024-05-20", "duedate": "2024-05-27", "pts": "100", "description": "Conduct a penetration test on a simulated network and submit a report that includes your methods, findings, and recommendations for improving security." },
        
    { "_id": "A137", "title": "Cloud Architecture Design", "course": "RS113", "available": "May 6 at 12:00am", "due": "Due May 13 at 11:59pm", "outdate": "2024-05-06", "duedate": "2024-05-13", "pts": "100", "description": "Design a cloud-based architecture for a company with scalability and security in mind. Submit both a detailed architecture diagram and a report." },
    { "_id": "A138", "title": "Serverless Computing Project", "course": "RS113", "available": "May 13 at 12:00am", "due": "Due May 20 at 11:59pm", "outdate": "2024-05-13", "duedate": "2024-05-20", "pts": "100", "description": "Implement a serverless application using AWS Lambda or Google Cloud Functions. Submit the source code along with a report explaining the architecture." },
    { "_id": "A139", "title": "Virtualization and Containerization Lab", "course": "RS113", "available": "May 20 at 12:00am", "due": "Due May 27 at 11:59pm", "outdate": "2024-05-20", "duedate": "2024-05-27", "pts": "100", "description": "Set up a containerized environment using Docker or Kubernetes and write a lab report that includes setup, deployment, and scaling strategies." },
        
    { "_id": "A140", "title": "Robotics Systems Design", "course": "RS114", "available": "May 6 at 12:00am", "due": "Due May 13 at 11:59pm", "outdate": "2024-05-06", "duedate": "2024-05-13", "pts": "100", "description": "Design a robotic system that performs a specific task, focusing on both hardware and software components. Submit the design along with a simulation or working prototype." },
    { "_id": "A141", "title": "Robot Kinematics Analysis", "course": "RS114", "available": "May 13 at 12:00am", "due": "Due May 20 at 11:59pm", "outdate": "2024-05-13", "duedate": "2024-05-20", "pts": "100", "description": "Analyze the kinematics of a robotic arm, including forward and inverse kinematics. Submit detailed calculations and simulation results." },
    { "_id": "A142", "title": "Autonomous Navigation Lab", "course": "RS114", "available": "May 20 at 12:00am", "due": "Due May 27 at 11:59pm", "outdate": "2024-05-20", "duedate": "2024-05-27", "pts": "100", "description": "Implement autonomous navigation for a robot using sensor data and path planning algorithms. Submit a report and the source code for the system." },
        
    { "_id": "A143", "title": "Electric Vehicle Design", "course": "RS115", "available": "May 6 at 12:00am", "due": "Due May 13 at 11:59pm", "outdate": "2024-05-06", "duedate": "2024-05-13", "pts": "100", "description": "Design an electric vehicle system, focusing on battery technology and efficiency. Submit a report detailing your design choices and potential improvements." },
    { "_id": "A144", "title": "Energy Storage Systems Analysis", "course": "RS115", "available": "May 13 at 12:00am", "due": "Due May 20 at 11:59pm", "outdate": "2024-05-13", "duedate": "2024-05-20", "pts": "100", "description": "Analyze different energy storage systems, comparing battery types and energy densities. Submit a report with your analysis and conclusions." },
    { "_id": "A145", "title": "Sustainable Energy Lab", "course": "RS115", "available": "May 20 at 12:00am", "due": "Due May 27 at 11:59pm", "outdate": "2024-05-20", "duedate": "2024-05-27", "pts": "100", "description": "Conduct an experiment on sustainable energy sources such as solar or wind. Submit a lab report with data analysis and conclusions." },
        
    { "_id": "A146", "title": "Big Data Analytics Assignment", "course": "RS116", "available": "May 6 at 12:00am", "due": "Due May 13 at 11:59pm", "outdate": "2024-05-06", "duedate": "2024-05-13", "pts": "100", "description": "Analyze a large dataset using Hadoop or Spark. Submit a report detailing your findings and the tools you used for data processing and analysis." },
    { "_id": "A147", "title": "Data Visualization Project", "course": "RS116", "available": "May 13 at 12:00am", "due": "Due May 20 at 11:59pm", "outdate": "2024-05-13", "duedate": "2024-05-20", "pts": "100", "description": "Create an interactive data visualization using a tool like Tableau or D3.js. Submit the project along with a report explaining the insights gained." },
    { "_id": "A148", "title": "Predictive Analytics Lab", "course": "RS116", "available": "May 20 at 12:00am", "due": "Due May 27 at 11:59pm", "outdate": "2024-05-20", "duedate": "2024-05-27", "pts": "100", "description": "Implement a predictive analytics model using Python or R. Submit the model code along with a report on its accuracy and potential applications." },
        
    { "_id": "A149", "title": "Internet of Things (IoT) System Design", "course": "RS117", "available": "May 6 at 12:00am", "due": "Due May 13 at 11:59pm", "outdate": "2024-05-06", "duedate": "2024-05-13", "pts": "100", "description": "Design an IoT system for home automation. Submit both a schematic of the system and a report explaining the technology used and its scalability." },
    { "_id": "A150", "title": "Embedded IoT Devices Lab", "course": "RS117", "available": "May 13 at 12:00am", "due": "Due May 20 at 11:59pm", "outdate": "2024-05-13", "duedate": "2024-05-20", "pts": "100", "description": "Build an IoT device using an embedded system such as Arduino or Raspberry Pi. Submit the source code along with a report detailing its operation." },
    { "_id": "A151", "title": "IoT Data Security Analysis", "course": "RS117", "available": "May 20 at 12:00am", "due": "Due May 27 at 11:59pm", "outdate": "2024-05-20", "duedate": "2024-05-27", "pts": "100", "description": "Analyze the security risks associated with IoT devices. Submit a report discussing potential vulnerabilities and strategies for securing IoT networks." },
        
    { "_id": "A152", "title": "Blockchain Technology Overview", "course": "RS118", "available": "May 6 at 12:00am", "due": "Due May 13 at 11:59pm", "outdate": "2024-05-06", "duedate": "2024-05-13", "pts": "100", "description": "Write a report on blockchain technology, explaining its underlying mechanisms and use cases. Include examples of applications and their impact on industries." },
    { "_id": "A153", "title": "Smart Contracts Development", "course": "RS118", "available": "May 13 at 12:00am", "due": "Due May 20 at 11:59pm", "outdate": "2024-05-13", "duedate": "2024-05-20", "pts": "100", "description": "Develop a smart contract using Solidity or another blockchain development language. Submit both the contract code and a report explaining its functionality." },
    { "_id": "A154", "title": "Cryptocurrency Systems Analysis", "course": "RS118", "available": "May 20 at 12:00am", "due": "Due May 27 at 11:59pm", "outdate": "2024-05-20", "duedate": "2024-05-27", "pts": "100", "description": "Analyze a cryptocurrency system, focusing on its consensus mechanism, security features, and scalability. Submit a report with your findings." },
        
    { "_id": "A155", "title": "Quantum Computing Concepts", "course": "RS119", "available": "May 6 at 12:00am", "due": "Due May 13 at 11:59pm", "outdate": "2024-05-06", "duedate": "2024-05-13", "pts": "100", "description": "Submit a report explaining the basics of quantum computing, including qubits, superposition, and quantum gates. Discuss potential applications and challenges." },
    { "_id": "A156", "title": "Quantum Algorithm Simulation", "course": "RS119", "available": "May 13 at 12:00am", "due": "Due May 20 at 11:59pm", "outdate": "2024-05-13", "duedate": "2024-05-20", "pts": "100", "description": "Simulate a quantum algorithm using Python or a quantum computing framework such as Qiskit. Submit the code and a report analyzing the results." },
    { "_id": "A157", "title": "Quantum Cryptography Lab", "course": "RS119", "available": "May 20 at 12:00am", "due": "Due May 27 at 11:59pm", "outdate": "2024-05-20", "duedate": "2024-05-27", "pts": "100", "description": "Conduct an experiment in quantum cryptography and submit a report discussing the principles and results. Include any code or simulations used." },
        
    { "_id": "A158", "title": "Advanced Game Development Project", "course": "RS120", "available": "May 6 at 12:00am", "due": "Due May 13 at 11:59pm", "outdate": "2024-05-06", "duedate": "2024-05-13", "pts": "100", "description": "Develop an advanced game using a game engine such as Unity or Unreal Engine. Submit the game project along with a report detailing its design and development process." },
    { "_id": "A159", "title": "Virtual Reality (VR) Development Lab", "course": "RS120", "available": "May 13 at 12:00am", "due": "Due May 20 at 11:59pm", "outdate": "2024-05-13", "duedate": "2024-05-20", "pts": "100", "description": "Create a VR experience using a game engine. Submit the source code along with a report on the technical challenges and solutions encountered during development." },
    { "_id": "A160", "title": "Game AI Implementation", "course": "RS120", "available": "May 20 at 12:00am", "due": "Due May 27 at 11:59pm", "outdate": "2024-05-20", "duedate": "2024-05-27", "pts": "100", "description": "Implement AI behavior for a game using techniques such as pathfinding, decision-making, and learning algorithms. Submit both the code and a report on the AI's performance." },
        
    { "_id": "A161", "title": "Advanced Algorithms Assignment", "course": "RS121", "available": "May 6 at 12:00am", "due": "Due May 13 at 11:59pm", "outdate": "2024-05-06", "duedate": "2024-05-13", "pts": "100", "description": "Submit an assignment on advanced algorithms, focusing on dynamic programming, graph algorithms, and complexity analysis. Include detailed solutions to the problem set." },
    { "_id": "A162", "title": "Data Structures and Algorithms Project", "course": "RS121", "available": "May 13 at 12:00am", "due": "Due May 20 at 11:59pm", "outdate": "2024-05-13", "duedate": "2024-05-20", "pts": "100", "description": "Implement a project involving data structures such as trees, graphs, and hash tables. Submit both the source code and a report on the performance analysis." },
    { "_id": "A163", "title": "Algorithm Optimization Lab", "course": "RS121", "available": "May 20 at 12:00am", "due": "Due May 27 at 11:59pm", "outdate": "2024-05-20", "duedate": "2024-05-27", "pts": "100", "description": "Optimize a given algorithm for both time and space complexity. Submit the optimized code along with a report on the improvements achieved." },
        
    { "_id": "A1", "title": "New Assignment", "course": "A1", "available": "May 20 at 12:00am", "due": "Due May 27 at 11:59pm", "outdate": "2024-05-20", "duedate": "2024-05-27", "pts": "100", "description": "New assignment" }
  ]